output "instance_arn" {
  description = "ARN of the instance which has been created"  
  value = aws_instance.desktop.arn
}

output "instance_priv_dns" {
  description = "DNS for private IP of instance"
  value = aws_instance.desktop.private_dns
}

output "vnc_password" {
  description = "VNC password as generated by the module"
  value = random_string.random_secret.result
}